#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run format
npm run fetch

git diff --quiet && git diff --staged --quiet || git add src/data/repos.json || git commit -m '🗃 Fetch GitHub repos'
