#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npm run lint
npm run format
npm run fetch
git add src/data/repos.json
git diff --quiet && git diff --staged --quiet || git commit -m '🗃 Fetch GitHub repos'
