name: Auto commit

on:
  schedule:
    - cron: '30 23 * * *'

jobs:
  no-activity-report:
    name: Report no activity on GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Append time to report.txt file
        run: date >> report.txt

      - name: Commit changes
        run: |
          git config --global user.name 'vikingviolinist'
          git config --global user.email 'vikingviolinist@users.noreply.github.com'
          git add report.txt
          git commit -m '🤖 Auto report no activity on GH'
          git push origin main
