name: Auto commit

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  no-activity-report:
    name: Report no activity on GitHub
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Append time to report.txt file
        run: date >> report.txt

      - name: Commit changes
        run: |
          git config --global user.name 'vikingviolinist'
          git config --global user.email 'vikingviolinist@users.noreply.github.com'
          git add report.txt
          git commit -m '🤖 Auto report no activity on GH'
          git push origin main

  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - run: "echo 'latest release: ${{ github.event.repository.owner.name }}'"
      - uses: octokit/graphql-action@v2.x
        id: get_latest_release
        with:
          query: |
            query release($owner:String!,$repo:String!) {
              repository(owner:$owner,name:$repo) {
                releases(first:1) {
                  nodes {
                    name
                    createdAt
                    tagName
                    description
                  }
                }
              }
            }
          owner: ${{ github.event.repository.owner.name }}
          repo: ${{ github.event.repository.name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: "echo 'latest release: ${{ steps.get_latest_release.outputs.data }}'"
